LABEL2ID_EVNER = {"B-DATE":0, "B-DURATION":1, "B-EVENT": 2, "B-SET": 3, "B-TIME": 4, "I-DATE":5, "I-DURATION":6, "I-EVENT":7, "I-SET":8, "I-TIME":9, "O":10}
ID2LABEL_EVNER = {0: 'B-DATE', 1: 'B-DURATION', 2: 'B-EVENT', 3: 'B-SET', 4: 'B-TIME', 5: 'I-DATE', 6: 'I-DURATION', 7: 'I-EVENT', 8: 'I-SET', 9: 'I-TIME', 10: 'O'}

LABEL2ID_EE = {"AFTER": 0, "BEFORE": 1, "CONTAINS": 2, "DURING":3, "EQUALS":4, "IDENTITY":5, "OVERLAPS":6}
ID2LABEL_EE = {0: 'AFTER', 1: 'BEFORE', 2: 'CONTAINS', 3: 'DURING', 4: 'EQUALS', 5: 'IDENTITY', 6: 'OVERLAPS'}

LABEL2ID_GEONER = {"B-LOCATION":0, "B-MINERAL":1, "B-ORE_DEPOSIT":2, "B-ROCK":3, "B-STRAT":4, "B-TIMESCALE":5, "I-LOCATION":6, "I-MINERAL":7, "I-ORE_DEPOSIT":8, "I-ROCK":9, "I-STRAT":10, "I-TIMESCALE":11, "O":12}
ID2LABEL_GEONER = {0: 'B-LOCATION', 1: 'B-MINERAL', 2: 'B-ORE_DEPOSIT', 3: 'B-ROCK', 4: 'B-STRAT', 5: 'B-TIMESCALE', 6: 'I-LOCATION', 7: 'I-MINERAL', 8: 'I-ORE_DEPOSIT', 9: 'I-ROCK', 10: 'I-STRAT', 11: 'I-TIMESCALE', 12: 'O'}

EVENT_TIME_NER_LABS = ["B-DATE", "B-DURATION", "B-EVENT", "B-SET", "B-TIME", "I-DATE", "I-DURATION", "I-EVENT", "I-SET", "I-TIME", "O"]
EE_TEMPREL_LABS = ["BEFORE", "AFTER", "DURING", "OVERLAPS", "CONTAINS", "SIMULTANEOUS", "IDENTITY"]

EVENT_BI = {2:7}
TIMEX_BI = {0:5, 1:6, 3:8, 4:9}
GEOENT_BI = {0:6, 1:7, 2:8, 3:9, 4:10}
GEOTIME_BI = {5:11}